// Generated by matugen — do not edit manually
var C = {
    primary:       "#afc6ff",
    onPrimary:     "#132f60",
    surface:       "#121318",
    surfaceCont:   "#1e1f25",
    surfaceContHi: "#282a2f",
    onSurface:     "#e2e2e9",
    onSurfaceVar:  "#c5c6d0",
    secondary:     "#bfc6dc",
    tertiary:      "#dfbbde",
    error:         "#ffb4ab",
    outline:       "#8f9099",
}
