$color_primary        = rgba(afc6ffff)
$color_primary_dim    = rgba(2d4678ff)
$color_secondary      = rgba(bfc6dcff)
$color_tertiary       = rgba(dfbbdeff)
$color_surface        = rgba(121318ff)
$color_outline        = rgba(8f909988)
$color_error          = rgba(ffb4abff)
