monitor = eDP-1, 1920x1200@180, 0x0, 1.066667

$terminal = foot
$fileManager = dolphin
$menu = fuzzel
$mainMod = SUPER

source = $HOME/.config/hypr/colors.conf
source = $HOME/.config/hypr/conf/env.conf
source = $HOME/.config/hypr/conf/autostart.conf
source = $HOME/.config/hypr/conf/look.conf
source = $HOME/.config/hypr/conf/input.conf
source = $HOME/.config/hypr/conf/binds.conf
source = $HOME/.config/hypr/conf/rules.conf
