// Generated by matugen — do not edit manually
var C = {
    primary:       "#{{colors.primary.default.hex_stripped}}",
    onPrimary:     "#{{colors.on_primary.default.hex_stripped}}",
    surface:       "#{{colors.surface.default.hex_stripped}}",
    surfaceCont:   "#{{colors.surface_container.default.hex_stripped}}",
    surfaceContHi: "#{{colors.surface_container_high.default.hex_stripped}}",
    onSurface:     "#{{colors.on_surface.default.hex_stripped}}",
    onSurfaceVar:  "#{{colors.on_surface_variant.default.hex_stripped}}",
    secondary:     "#{{colors.secondary.default.hex_stripped}}",
    tertiary:      "#{{colors.tertiary.default.hex_stripped}}",
    error:         "#{{colors.error.default.hex_stripped}}",
    outline:       "#{{colors.outline.default.hex_stripped}}",
}
