bind = $mainMod, Space,              exec, $menu
bind = $mainMod, S,                  exec, qs ipc call bar toggleSettings
bind = $mainMod SHIFT, B,           exec, $HOME/.config/hypr/scripts/toggle-bar.sh
bind = $mainMod SHIFT, C,           exec, hyprpicker -a -f hex
bind = $mainMod, R,           exec, $HOME/.local/bin/zerochan-wallpaper
bindr = SUPER, Super_L,       exec, $menu
bind = $mainMod, T,           exec, $terminal
bind = $mainMod, Escape,      exec, foot -e btop
bind = $mainMod, E,           exec, $fileManager
bind = $mainMod, W,           exec, zen-browser
bind = $mainMod SHIFT, W,     exec, waypaper
bind = $mainMod, P,           exec, playerctl play-pause
bind = $mainMod, O,           exec, playerctl next
bind = $mainMod, I,           exec, playerctl previous

bind = $mainMod, Q,           killactive
bind = $mainMod, D,           togglefloating
bind = $mainMod, F,           fullscreen
bind = $mainMod, V,           exec, cliphist list | fuzzel -d | cliphist decode | wl-copy

bind = $mainMod ALT, left,    movewindow, l
bind = $mainMod ALT, right,   movewindow, r
bind = $mainMod ALT, up,      movewindow, u
bind = $mainMod ALT, down,    movewindow, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod ALT, 1, movetoworkspace, 1
bind = $mainMod ALT, 2, movetoworkspace, 2
bind = $mainMod ALT, 3, movetoworkspace, 3
bind = $mainMod ALT, 4, movetoworkspace, 4
bind = $mainMod ALT, 5, movetoworkspace, 5
bind = $mainMod ALT, 6, movetoworkspace, 6
bind = $mainMod ALT, 7, movetoworkspace, 7
bind = $mainMod ALT, 8, movetoworkspace, 8
bind = $mainMod ALT, 9, movetoworkspace, 9
bind = $mainMod ALT, 0, movetoworkspace, 10

bind = CTRL ALT, right,           workspace, e+1
bind = CTRL ALT, left,            workspace, e-1
bind = $mainMod, mouse_down,      workspace, e+1
bind = $mainMod, mouse_up,        workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bindel = , XF86AudioRaiseVolume,  exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && qs ipc call bar osdVolume
bindel = , XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && qs ipc call bar osdVolume
bindl  = , XF86AudioMute,         exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && qs ipc call bar osdVolume
bindl  = , XF86AudioMicMute,      exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl  = , XF86AudioPlay,         exec, playerctl play-pause
bindl  = , XF86AudioNext,         exec, playerctl next
bindl  = , XF86AudioPrev,         exec, playerctl previous

bindel = $mainMod, bracketright,  exec, brightnessctl s 5%+ && qs ipc call bar osdBrightness
bindel = $mainMod, bracketleft,   exec, brightnessctl s 5%- && qs ipc call bar osdBrightness
bindel = , XF86MonBrightnessUp,   exec, brightnessctl s 5%+ && qs ipc call bar osdBrightness
bindel = , XF86MonBrightnessDown, exec, brightnessctl s 5%- && qs ipc call bar osdBrightness

bind = , Print,               exec, grim - | wl-copy && notify-send -i screenshot "Screenshot" "Fullscreen copied to clipboard"
bind = CTRL, F12,             exec, grim - | wl-copy && notify-send -i screenshot "Screenshot" "Fullscreen copied to clipboard"
bind = $mainMod SHIFT, S,     exec, grim -g "$(slurp)" - | wl-copy && notify-send -i screenshot "Screenshot" "Region copied to clipboard"

bind = $mainMod, L,           exec, hyprctl switchxkblayout all 0 && hyprlock
bind = $mainMod SHIFT, L,     exec, wlogout -b 3 -c 0 -r 0 -m 0
bind = CTRL ALT, Delete,      exec, wlogout -b 3 -c 0 -r 0 -m 0
